'use strict';

module.exports = {
  creds: {
    username: 'admin',
    password: 'bacon10',
    baseurl: 'http://x.bobo.com'
  },
  app_rules: [{
    'id': '4a0efb33-fbc3-11e3-bdd2-3c0754664458',
    'category': 'Communication',
    'version_string': '',
    'package_name': 'com.whatsapp',
    'certificate': null,
    'creator': 'WhatsApp Inc.',
    'mobile_app_id': '4a0efb33-fbc3-11e3-bdd2-3c0754664458',
    'source_id': null,
    'installsize': '',
    'system_flag': false,
    'versioncode': '',
    'title': 'WhatsApp Messenger',
    'm_hash': '',
    'tags': [],
    'download_url': null,
    'source': 'googleplay',
    'activator': null,
    'blocker': null,
    'tag_name': '',
    'is_support': false,
    'is_certified': false,
    'platform': 'android',
    'vpp_total': 0,
    'vpp_used': 0,
    'icon_url': 'https://icons-mobilespaces.s3.amazonaws.com/com.whatsapp.png',
    'network_access': 'direct',
    'rule_type': 'add',
    'versioncode_target': '0'
  }, {
    'id': '32c22451-8480-11e3-81bb-b8f6b1101425',
    'category': '',
    'version_string': '',
    'package_name': 'be.bogus',
    'certificate': '',
    'creator': 'Mr Bogus',
    'mobile_app_id': '32c22451-8480-11e3-81bb-b8f6b1101425',
    'source_id': '',
    'installsize': '',
    'system_flag': false,
    'versioncode': '',
    'title': 'Be Bogus',
    'm_hash': '',
    'tags': [],
    'download_url': '',
    'source': 'enterprise',
    'activator': 'something',
    'blocker': '',
    'tag_name': '',
    'is_support': false,
    'is_certified': false,
    'platform': 'android',
    'vpp_total': 0,
    'vpp_used': 0,
    'icon_url': 'https://icons-mobilespaces.s3.amazonaws.com/https://icons-mobilespaces.s3.amazonaws.com/be.bogus.png',
    'network_access': 'direct',
    'rule_type': 'add',
    'versioncode_target': '2'
  }],
  policy: {
    'created_on': '',
    'display_name': '',
    'state': 'edited',
    'group_id': '0',
    'id': '',
    'modified_on': '',
    'name': 'Nexus_5_02c8ff6c213e4d7c',
    'query': 'tags: Nexus_5_02c8ff6c213e4d7c',
    'seq': '3',
    'edited': true
  },
  user: {
    'workspace_email': 'scott+apitest@fatlatte.us',
    'created_on': '',
    'display_name': '',
    'emails': '',
    'full_name': 'Nexus_5_02c8ff6c213e4d7c',
    'group_id': '',
    'group_name': '',
    'location_id': '',
    'location_name': '',
    'locked': '',
    'modified_on': '',
    'phone_number': '',
    'provision_email': 'scott+apitest@fatlatte.us',
    'role': 'USER_ROLE',
    'role_label': 'User',
    'username': 'Nexus_5_02c8ff6c213e4d7c',
    'tags': ['Nexus_5_02c8ff6c213e4d7c'],
    'spaces': '',
    'send_welcome_sms': false,
    'send_welcome_email': false,
    'create_space': false
  }
};